# Generated by Django 4.1 on 2022-09-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_is_finised_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_finised',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
